services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "13001:8181"
    command:
      - influxdb3
      - serve
      - --node-id=dowob  # 填寫您的節點ID
      - --object-store=file # 使用文件存儲
      - --data-dir=/var/lib/influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_USER: myuser
      INFLUXDB_USER_PASSWORD: mypassword

  influxdb-gui:
    image: quay.io/influxdb/influxdb3-explorer:latest
    container_name: influxdb-gui
    restart: unless-stopped
    ports:
      - "13002:80"
    command:
      - --mode=admin
    volumes:
      - ./influxdb-gui/config:/app-root/config:ro
      - ./influxdb-gui/db:/db:rw
    environment:
      INFLUXDB_URL: http://influxdb:8181
      INFLUXDB_TOKEN: your_influxdb_token_here  # 替換為您的InfluxDB令牌
    depends_on:
      - influxdb

  chart-kafka:
    image: bitnami/kafka:latest
    container_name: chart-kafka
    ports:
      - "13003:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:13003"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_KRAFT_CLUSTER_ID: "kraft-1"
    volumes:
      - ./kafka_data:/bitnami/kafka
    restart: unless-stopped