name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        # Use setup script to install all available modules
        bash setup.sh
    
    - name: Run linting
      run: |
        source .venv/bin/activate
        ruff check .
        ruff format --check .
    
    - name: Run type checking
      run: |
        source .venv/bin/activate
        mypy .
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        # Use unified test engine for consistent testing
        bash scripts/test-engine.sh --ci-mode
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false